version: '3'

services:

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: mrp_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/db-data/:/var/lib/postgresql/data/